# Two static web servers on the WAN network.
services:
  web1:
    build: ./web1
    container_name: netplay_web1
    networks:
      wan:
        ipv4_address: 172.20.0.100
    restart: unless-stopped

  web2:
    build: ./web2
    container_name: netplay_web2
    networks:
      wan:
        ipv4_address: 172.20.0.101
    restart: unless-stopped

  dns:
    build: ./dns
    container_name: netplay_dns
    networks:
      lan:
        ipv4_address: 10.0.0.2
    restart: unless-stopped

networks:
  lan:
    name: netplay_lan
    ipam:
      config:
        - subnet: 10.0.0.0/24
  wan:
    name: netplay_wan
    ipam:
      config:
        - subnet: 172.20.0.0/24
